network:
  ethernets:
    enp6s18:
      dhcp4: false
      addresses:
        - 192.168.99.14/24
      nameservers:
          addresses:
            - 192.168.99.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.99.1
        metric: 99
    enp6s19:
      dhcp4: true
      dhcp-identifier: mac
  version: 2
