---
- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
- name: Install Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
- name: Create log destination
  ansible.builtin.file:
    name: "{{ log_path }}"
    state: directory
    owner: caddy
    group: caddy
- name: Install CA Cert
  ansible.builtin.shell:
    cmd: cp "{{ ca_cert_src }}" "{{ ca_cert_dest }}"
    creates: "{{ ca_cert_dest }}"
- name: Fix cert permission
  ansible.builtin.file:
    name: "{{ ca_cert_dest }}"    
    owner: caddy
    group: caddy
    mode: 0400
- name: Ensure webroot permissions
  ansible.builtin.file:
    state: directory
    path: "{{ webroot }}"
    owner: caddy
    group: caddy
- name: Restart/Enable Caddy (reverse proxy)
  ansible.builtin.systemd_service:
    name: caddy
    enabled: true
    state: restarted
  when: caddy_mode == 'reverse_proxy'
- name: Add web content
  ansible.builtin.template:
    src: index.html.j2 
    dest: "{{ webroot }}/index.html"
    owner: caddy
    group: caddy
    mode: 0644
  when: "caddy_mode == 'normal'"
  notify: 
    - Restart/Enable Caddy
- name: Convert to PHP
  import_tasks: php.yml
  when: "mode == 'php'"
